### PR TITLE
Animation challenge - Josue

### PR DESCRIPTION
**Pull request by jghg02**
https://user-images.githubusercontent.com/1470487/180671019-edff1041-2363-45d5-91f9-587b1d3d21d2.mp4

In this folder `ImagePreviews/JosueH-AnimationChallenge1` has all code

### CODE REVIEW

**Comment by DaemonLoki** [comment]
Nice work, @jghg02!

I love the creative way of having different colors and their dynamic changes, awesome job! :) 

One thing I would like to ask you: is it possible that you could add the entire Xcode project together with the video?
It's easier for newcomers to browse and run the code and we'd have a unified look and feel of the repo. That would be really cool! :) 

Thanks in any case for the submission, can't wait to explore the solution more and see how you've done it! :)

Best,
Stefan

**Comment by jghg02** [comment]
Sure @DaemonLoki

**Review by amosgyamfi — APPROVED** [review]
I love the randomness of the colors you added on top. The code is also simple and understandable.

**Comment by yogirajthombre** [comment]
Hey @jghg02 animation looks awesome

**Review by DaemonLoki — APPROVED** [review]

**Pull request merged**
