### PR TITLE
Spotify Animation

### PR DESCRIPTION
**Pull request by Silviuvr**
https://user-images.githubusercontent.com/96594955/178953629-72010b6f-b047-47dc-97a4-5bdd4b338df1.mp4

### CODE REVIEW

**Comment by DaemonLoki** [comment]
Hey @Silviuvr!

Thanks for your submission, that looks really great! :) 

One thing I'm asking of you: Could you add the code to your solution to the repo as well? You can simply create a folder with your name and drop the Xcode project inside. 😇

We want to compare solutions and let other people learn from the different approaches, so it would be great to see your submission and the code you used to create it. :) 

Thanks already and I can't wait to see how you solved the challenge! :)

**Comment by Silviuvr** [comment]
> Hey @Silviuvr!
> 
> Thanks for your submission, that looks really great! :)
> 
> One thing I'm asking of you: Could you add the code to your solution to the repo as well? You can simply create a folder with your name and drop the Xcode project inside. 😇
> 
> We want to compare solutions and let other people learn from the different approaches, so it would be great to see your submission and the code you used to create it. :)
> 
> Thanks already and I can't wait to see how you solved the challenge! :)

Hey! No problem. I just pushed it. Just a question.
I noticed that there are some weird files that were added and git ignore could not remove them( lots of Contents.json and other files). Maybe that's how it supposed to be just curious. 

Have a good day!

**Comment by DaemonLoki** [comment]
Awesome job! :)

You are right, the `Contents.json` might look weird. But it is the Xcode is handling certain assets like images. It has to do with the way different resolutions of images are used for different devices.

But these are necessary that Xcode can manage the project correctly. I saw that you pulled the `.gitignore` file from gitignore.io. I'm also always using that for generating those and they are great. :) 

So, everything looks good. Configuration is all correct. :)

**Comment by amosgyamfi** [comment]
Interesting solution. Looking at the animation alone, I never realized you are using Spring Animation.

**Review by DaemonLoki — APPROVED** [review]

**Pull request merged**
