### PR TITLE
Sahil Sahu Submission

### PR DESCRIPTION
**Pull request by sahil-sahu-dev**

### CODE REVIEW

**Comment by DaemonLoki** [comment]
Awesome job! :) 

Thanks for the submission, that's exactly what I was talking about in the previous PR! 
Just a quick note: In your submission there is a few files that don't necessarily need to be there (e.g. the `.DS_STORE` files from macOS).

You can create nice `.gitignore` files from e.g. [this site](http://www.gitignore.io). [Here is one](https://www.toptal.com/developers/gitignore/api/macos,swift,xcode) I normally use for iOS projects.

Just as a quick tip. 💡

**Comment by sahil-sahu-dev** [comment]
Great tip! I'll be sure to use that next time

**Comment by amosgyamfi** [comment]
Nice submission. I like how you used a different approach to solve it.

**Comment by sahil-sahu-dev** [comment]
Thank you!

**Review by DaemonLoki — APPROVED** [review]

**Pull request merged**
